global:
  scrape_interval: 15s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'telegram_exporter'
  static_configs:
    - targets: ['telegram-monitor:8000']  # Имя сервиса и порт в Docker Compose