global:
  scrape_interval: 5s  # Интервал сбора метрик
  evaluation_interval: 5s # Интервал проверки правил(???)

scrape_configs:
- job_name: "monitor"
  static_configs:
  - targets: ["telegram_monitor:8000"]  # Имя сервиса и порт в Docker Compose